#define CONTROL_DEVICE_NAME L"\\Device\\FDLVLCTL_D7E51260_2063_4761_9933_416742467721"
#define CONTROL_DOSDEVICE_NAME L"\\DosDevices\\FDLVLCTL_D7E51260_2063_4761_9933_416742467721"

NTSTATUS CreateControlDevice(PDRIVER_OBJECT DriverObject);
NTSTATUS CreateAnotherDevice(PDEVICE_OBJECT OriginalDeviceObject,
                             PDEVICE_OBJECT* AnotherDeviceObject);
NTSTATUS ControlDispatch(PDEVICE_OBJECT DeviceObject, PIRP Irp);

typedef struct _DEVICE_EXTENSION_CONTROL DEVICE_EXTENSION_CONTROL, *PDEVICE_EXTENSION_CONTROL;
struct _DEVICE_EXTENSION_CONTROL {
	BOOLEAN IsControlDevice;
	BOOLEAN IsAnotherDevice;
	PDEVICE_OBJECT OriginalDeviceObject;
};
