#include "headers.h"

NTSTATUS CreateControlDevice(PDRIVER_OBJECT DriverObject) {
	NTSTATUS status;
	PDEVICE_EXTENSION_CONTROL DeviceExtension;
	PDEVICE_OBJECT DeviceObject = NULL;
	UNICODE_STRING DeviceName;
	UNICODE_STRING SymbolicName;
	RtlUnicodeStringInit(&DeviceName, CONTROL_DEVICE_NAME);
	RtlUnicodeStringInit(&SymbolicName, CONTROL_DOSDEVICE_NAME);
	status = IoCreateDeviceSecure(DriverObject, sizeof(DEVICE_EXTENSION_CONTROL), &DeviceName,
	                              FILE_DEVICE_UNKNOWN, FILE_DEVICE_SECURE_OPEN, FALSE,
	                              &SDDL_DEVOBJ_SYS_ALL_ADM_ALL, NULL, &DeviceObject);
	if(!NT_SUCCESS(status)) {
		TRACE(LVL_ERROR, "IoCreateDeviceSecure()=%s", NtStatusName(status));
		KdBreakPoint();
		return status;
	}
	status = IoCreateSymbolicLink(&SymbolicName, &DeviceName);
	if(!NT_SUCCESS(status)) {
		TRACE(LVL_ERROR, "IoCreateSymbolicLink()=%s", NtStatusName(status));
		KdBreakPoint();
		IoDeleteDevice(DeviceObject);
		return status;
	}
	DeviceExtension = DeviceObject->DeviceExtension;
	RtlZeroMemory(DeviceExtension, sizeof(DEVICE_EXTENSION_CONTROL));
	DeviceExtension->IsControlDevice = TRUE;
	DeviceObject->Flags |= DO_DIRECT_IO;
	DeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
	return STATUS_SUCCESS;
}

NTSTATUS CreateAnotherDevice(PDEVICE_OBJECT OriginalDeviceObject,
                             PDEVICE_OBJECT* AnotherDeviceObject) {
	NTSTATUS status;
	PDRIVER_OBJECT DriverObject = OriginalDeviceObject->DriverObject;
	PDEVICE_EXTENSION_CONTROL DeviceExtension;
	PDEVICE_OBJECT DeviceObject = NULL;
	status = IoCreateDeviceSecure(DriverObject, sizeof(DEVICE_EXTENSION_CONTROL), NULL,
	                              FILE_DEVICE_UNKNOWN, FILE_DEVICE_SECURE_OPEN | FILE_AUTOGENERATED_DEVICE_NAME, FALSE,
	                              &SDDL_DEVOBJ_KERNEL_ONLY, NULL, &DeviceObject);
	if(!NT_SUCCESS(status)) {
		TRACE(LVL_ERROR, "IoCreateDeviceSecure()=%s", NtStatusName(status));
		KdBreakPoint();
		return status;
	}
	status = IoRegisterShutdownNotification(DeviceObject);
	if(!NT_SUCCESS(status)) {
		TRACE(LVL_ERROR, "IoRegisterShutdownNotification()=%s", NtStatusName(status));
		KdBreakPoint();
		IoDeleteDevice(DeviceObject);
		return status;
	}
	DeviceExtension = DeviceObject->DeviceExtension;
	RtlZeroMemory(DeviceExtension, sizeof(DEVICE_EXTENSION_CONTROL));
	DeviceExtension->IsControlDevice = TRUE;
	DeviceExtension->IsAnotherDevice = TRUE;
	DeviceExtension->OriginalDeviceObject = OriginalDeviceObject;
	*AnotherDeviceObject = DeviceObject;
	DeviceObject->Flags |= DO_DIRECT_IO;
	DeviceObject->Flags &= ~DO_DEVICE_INITIALIZING;
	return STATUS_SUCCESS;
}

void trace_control(PDEVICE_OBJECT DeviceObject, int* dst, int length) {
	UNICODE_STRING SymbolicName;
	if(8 == length) {
		int v = dst[1];
		switch(dst[0]) {
		case 0:
			trace_lvl = v;
			TRACE(2, "trace level=%x", trace_lvl);
			break;
		case 1:
			trace_lvl_function = v;
			TRACE(2, "function trace level=%x", trace_lvl_function);
			break;
		case 2:
			RtlUnicodeStringInit(&SymbolicName, CONTROL_DOSDEVICE_NAME);
			IoDeleteSymbolicLink(&SymbolicName);
			IoDeleteDevice(DeviceObject);
			TRACE(2, "control device deleted");
			break;
		}
	}
}

NTSTATUS ControlDispatch(PDEVICE_OBJECT DeviceObject, PIRP Irp) {
	PDEVICE_EXTENSION_CONTROL DeviceExtension = DeviceObject->DeviceExtension;
	PIO_STACK_LOCATION IrpStack = IoGetCurrentIrpStackLocation(Irp);
	PVOID SystemAddress;
	if(DeviceExtension->IsAnotherDevice) {
		Irp->IoStatus.Status = STATUS_SUCCESS;
		IoCompleteRequest(Irp, IO_NO_INCREMENT);
		return STATUS_SUCCESS;
	}
	switch(IrpStack->MajorFunction) {
	case IRP_MJ_READ:
		SystemAddress = MmGetSystemAddressForMdlSafe(Irp->MdlAddress, NormalPagePriority);
		Irp->IoStatus.Information = trace_read(SystemAddress, IrpStack->Parameters.Read.Length);
		break;
	case IRP_MJ_WRITE:
		SystemAddress = MmGetSystemAddressForMdlSafe(Irp->MdlAddress, NormalPagePriority);
		trace_control(DeviceObject, SystemAddress, IrpStack->Parameters.Write.Length);
		break;
	}
	Irp->IoStatus.Status = STATUS_SUCCESS;
	IoCompleteRequest(Irp, IO_NO_INCREMENT);
	return STATUS_SUCCESS;
}
